version: 2.1

commands:
  test-nodejs-legacy:
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test:ci:legacy
  test-nodejs:
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test:ci
jobs:
  node-v6:
    docker:
      - image: node:6
    steps:
      - test-nodejs-legacy
  node-v8:
    docker:
      - image: node:8
    steps:
      - test-nodejs-legacy
  node-v10:
    docker:
      - image: node:10
    steps:
      - test-nodejs
  node-v12:
    docker:
      - image: node:12
    steps:
      - test-nodejs
  node-v14:
    docker:
      - image: node:14
    steps:
      - test-nodejs

workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v6
      - node-v8
      - node-v10
      - node-v12
      - node-v14
