name: CI-jest

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10, 12, 14, 15, 16]
        os: [ubuntu-latest]
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install --ignore-scripts

      - name: Run Tests
        run: |
          npm run test:jest
